### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by mimbres** [mimbres/neural-audio-fp#8]

**Comment by guillemcortes** [comment]
Hi, it might be related to this, but I'm trying to generate fingerprints from custom source using the pretranied model you shared here: https://github.com/mimbres/neural-audio-fp/issues/10#issuecomment-878335408 and I was wondering if you could tell me what's the expectated time for generating a fingerprint from a single query? Since it took 1629seconds to generate fingerprints corresponding to 2 queries (1-min length) [even though in the source directory there are 3 wav files, I'm studying why this as well ]
`From the CLI Output: 2/2 [==============================] - 1629s 47ms/step`

I'm using a 40-cpu server with a RTX3090.

Also, can you help me understanding the shape of the resulting db? I understand that the shape is `n_items x d`, and `n_items` is `#num audios x batchsize`. I don't see what this batchsize mean and therefore, the resulting db shape.

Thanks in advance!

**Comment by mimbres** [comment]
@guillemcortes I opened the issue as a question #23.
